Pr view
E-corp-io/Git-Tracker pull request #22
Opened 2024-04-16 20:40 UTC by DavidJones1102

Show comments to pr,
add clicable pr link

2024-04-16 20:58 UTC, M0rgho commented
good PR, hovever I'm requesting a couple changes:
    - boundaries between commits are not clear, split them with maybe a horizontal line, or some other way to distinguish them
    - some comments can be pretty long, this can cause annoying scrolling - create a character limit for comment and replace the overflow with "..." 
    - add some color to distinguish open and closed PRs, don't sort them I'll do it later

2024-04-16 21:01 UTC, M0rgho requested changes
missclick, changes requested in previous comment

2024-04-16 21:45 UTC, DavidJones1102 commented
> good PR, hovever I'm requesting a couple changes: - boundaries between commits are not clear, split them with maybe a horizontal line, or some other way to distinguish them - some comments can be pretty long, this can cause annoying scrolling - create a character limit for comment and replace the overflow with "..." - add some color to distinguish open and closed PRs, don't sort them I'll do it later

I couldn't color open pr because pr.isMerged() is always false. It needs to be repaired in future.
I applied other suggestions

2024-04-16 21:47 UTC, DavidJones1102 commented on src/main/java/com/io/gittracker/controllers/RepositoryPresenter.java
> +                                                                : prComment.body()));
spotlessApply made this weird formatting

2024-04-17 08:38 UTC, M0rgho approved these changes
good

2024-04-17 08:39 UTC, merged